### ISSUE TITLE
code update

### ISSUE THREAD

**Issue by mrzl** [bfelbo/DeepMoji#1]
Hey there :ribbon:,

the paper to this repository looks amazing and I would love to have some possibility to experiment with it hands on. Are you still planning to release some code and pre-trained models here?

Many thanks :handshake:,
Marcel

**Comment by transfluxus** [comment]
👏
🤙

**Comment by thomwolf** [comment]
Indeed !! cc @julien-c

**Comment by bfelbo** [comment]
Thanks for your interest! Yes, we're definitely planning on releasing our pretrained model along with code examples. The code release is currently being reviewed by MIT's licensing office. It'll be released as soon as they're done with their review.

**Comment by bfelbo** [comment]
The code and model is available now. Sorry about the delay!
