### ISSUE TITLE
Issue in IMDB example

### ISSUE THREAD

**Issue by anujgupta82** [bfelbo/DeepMoji#10]
https://github.com/bfelbo/DeepMoji/blob/master/examples/imdb_from_scratch.py#L11

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
ipython-input-7-949a75e33038> in module>()
        4 from keras.preprocessing import sequence
        5 from keras.datasets import imdb
----> 6 from deepmoji.model_def import DeepMoji

**ImportError: cannot import name DeepMoji**

_when I open deepmoji.model_def file, there is no function named "DeepMoji"_

Am I missing something ?

**Comment by bfelbo** [comment]
Thanks a lot for reporting this. We've must have missed that when renaming the function to `deepmoji_architecture()`. It's been fixed now.
