### ISSUE TITLE
Unable to open file: /model/deepmoji_weights.hdf5'

### ISSUE THREAD

**Issue by xiao666** [bfelbo/DeepMoji#11]
HI,
I tried the "score_texts_emojis.py" in example directory.
But seems it lack the hdf5 file in model directory?

**Comment by edvoinea** [comment]
hdf5 is a module if I remember correctly. you could try to install it with pip

**Comment by xiao666** [comment]
Hi, thank you for the reply! I installed the hdf5, and the lack file is "deepmoji_weights.hdf5"
Here is the error output:
OSError: Unable to open file (Unable to open file: name = 'd:\clone_github\deepmoji36/model/deepmoji_weights.hdf5', errno = 2, error message = 'no such file or directory', flags = 0, o_flags = 0)

**Comment by devarsh13** [comment]
Try running download_weights.py from scrips folder.

**Comment by xiao666** [comment]
thank you @devarsh13, it works now!
