### ISSUE TITLE
Training Time?

### ISSUE THREAD

**Issue by ryanleary** [bfelbo/DeepMoji#21]
Just wondering if you had rough figures on how long it took to train the released model (type/number of GPUs, epochs, total time?) I'm hoping to build a similar corpus and just trying to plan while the data collects. Thanks.

**Comment by PeterPanUnderhill** [comment]
Same question here :)

**Comment by bfelbo** [comment]
It really depends on how long you're willing to wait. With this kind of corpus it seems that you can keep on squeezing out a tiny bit of extra performance the longer you run it. I trained the model on a single titan GPU. If I recall correctly, it took around 10 days until my early stopping criteria triggered.

Out of curiosity, why do you want to collect your own corpus and train it yourself? Part of the idea with this project was that I felt someone had to create a VGG-like model for text such that others could easily do emotion-related NLP without too much effort. That's also why we gave our model/code an MIT license and made it easy to use.

**Comment by PeterPanUnderhill** [comment]
Thanks @bfelbo for your reply. It's because that I want to train the model on another language, therefore the weights that are trained for English could not be used for my task (as far as I know). Anyway, many thanks for sharing the code and model!

**Comment by ryanleary** [comment]
Thanks that's very helpful!

**Comment by yaireclipse** [comment]
@bfelbo do you happen to remember how many epochs did it take? I don't need an exact number, just roughly - 5-10 or a few dozens?

**Comment by bfelbo** [comment]
I don't recall. However, we had so many tweets and did a lot of dynamic class rebalancing so epochs don't really capture it. I think the training time mentioned above would be a more useful measure.

**Comment by yaireclipse** [comment]
oh, I wasn't aware that the class rebalancing was dynamic...
Did you consider using multiple GPUs for the training to speed things up?
