### ISSUE TITLE
Unable to freeze Bidirectional Layer

### ISSUE THREAD

**Issue by limiao06** [bfelbo/DeepMoji#23]
I've run the script "examples/finetune_youtube_last.py". The trainable weights should be the last layer, but I found the Bidirectional layers are not frozen. I use tensorflow 1.3.0 as backend, and the keras version is 2.0.9.

![image](https://user-images.githubusercontent.com/12964198/34473476-2a658eaa-efae-11e7-955f-fecc8eddaafb.png)

**Comment by bfelbo** [comment]
Strange. This was initially an issue with how Keras handled trainability, but we fixed that with these lines: https://github.com/bfelbo/DeepMoji/blob/master/deepmoji/finetuning.py#L162. When I run the example using Theano and either Keras 2.0.8 or Keras 2.1.2 it works fine. So it seems to be an issue with the Tensorflow backend.

I don't have time to look more into it right now, but I'll take a closer look in a few days. Could you try switching to Theano and see if it helps you?

**Comment by bfelbo** [comment]
Also, make sure to update your Keras in case 2.0.9 introduced any issues.

**Comment by limiao06** [comment]
I update the Keras to 2.1.2 and the bug fixed. Thanks very much.
