### ISSUE TITLE
Error when running encode_texts.py

### ISSUE THREAD

**Issue by jungletech** [bfelbo/DeepMoji#26]
After running encode_texts.py, I see the output to the terminal but I get this error before the output file is created.

`Traceback (most recent call last):
  File "score_texts_emojis.py", line 20490, in <module>
    t_tokens = tokenized[i]
IndexError: index 20407 is out of bounds for axis 0 with size 20407`

**Comment by bfelbo** [comment]
It seems like you modified the example script. Is that the case? If so, how did you modify it?

**Comment by jungletech** [comment]
I changed it to be a new data set that I have.

**Comment by jungletech** [comment]
I want to make sure I am understanding this correctly, if I want to try with a new data set- I change code in two places, I change the reference file in create_twitter_vocab.py and put it in the test output for score_texts_emojis

**Comment by bfelbo** [comment]
It seems like you might have lost some sentences in the tokenization process (i.e. `tokenized, _, _ = st.tokenize_sentences(TEST_SENTENCES)`). That can happen if the sentences are empty or similar. I would check that `len(tokenized) = len(TEST_SENTENCES)` after tokenization and find out what kind of problems your sentences have. Makes sense?

**Comment by jungletech** [comment]
Oh yes that makes perfect sense- thank you so much! I’ll test it tomorrow morning first thing

**Comment by jungletech** [comment]
Just to make sure I am clear, I take my dataset and I load it in  create_twitter_vocab.py

Then when I want to see what emojis would be assigned to each individual element in the dataset, I place them in test sentences. 

And what you are saying is that the two should match, correct?

**Comment by bfelbo** [comment]
There's no need to create your own vocab using `create_twitter_vocab.py`. You can just use `score_texts_emojis.py`. The previous comment I made was about `score_texts_emojis.py`.

**Comment by bfelbo** [comment]
There might be an issue if you have sentences that only contain non-ASCII words. These words are removed. If the sentence is then empty, it's ignored and thereby `len(tokenized) = len(TEST_SENTENCES` is no longer valid. I would suggest you make sure that you only have English sentences in the dataset.

**Comment by bfelbo** [comment]
I hope my answer helped you solve the issue. Please feel free to reopen the issue if you're still having problems.
