### ISSUE TITLE
Error when attempting to use either Theano and Tensorflow

### ISSUE THREAD

**Issue by PJAMESR** [bfelbo/DeepMoji#27]
Hello,

So I have been trying to solve these problems for a while. I am running Python 2.7 64 bit on Windows. When I try to use Tensorflow, when I run nose tests for it I think I get "No Module named Tensorflow", an error message relating to Tensorflow being a different version maybe than the one that is being searched for by the test itself (specifically some file not reading version 5 but version six), but couldn't figure out that one. 

Anyways, so I am now attempting to use Theano, and have reinstalled multiple times, but the nose test just keeps giving me "ImportError: No module named Theano" so clearly this problem is the same. Do I need to install the directory somewhere specific?
If it makes any difference, I am downloading the zip files instead of cloning. 
Any ideas? I am going to go and try to install this on Mac on another computer and see if that works, but I would really prefer to install it on my own.

**Comment by bfelbo** [comment]
This does not seem to be related to DeepMoji, but rather to your Theano/Tensorflow installation. Most likely you have multiple version installed in different directories and your PATH is linking to the wrong one. Before playing around with DeepMoji, I would suggest you run a simple python script that prints the Tensorflow/Theano version to check that it's being properly loaded and is the newest version.

**Comment by PJAMESR** [comment]
All right, that is quite possible, let me check that out, Ill get back to you ASAP.

**Comment by PJAMESR** [comment]
So, I managed to figure this out and work through a bunch of issues after this. Basically, I needed to download Theano using pip instead of conda. 

But now I am getting errors when trying to do the full nose check in the form of not being able to complete the fine tuning using full, it just takes a REALLY long time and then says FAIL. Any idea on this one? I'm so close to fixing all the issues!

**Comment by bfelbo** [comment]
Deep learning models can take very long to train/finetune if you're not using a GPU. Either make sure you're using your GPU or only use the scripts that do not involve any training/finetuning such as https://github.com/bfelbo/DeepMoji/blob/master/examples/encode_texts.py
