### ISSUE TITLE
Errors importing data from a csv file with Unicode decoding: Any Ideas? 

### ISSUE THREAD

**Issue by PJAMESR** [bfelbo/DeepMoji#28]
Hey everyone, so I finally have gotten past some erros encoding my data in a csv to Unicode so that my data can be scored. I am using the score-texts-emoji file in examples to try and attempt this. 

Now I am getting problems decoding bytes within my file and I was wondering what the soution might be for this and if anyone has run into this problem. Here is what my code looks like : 

```
TEST_SENTENCES = []
with open('Cleaned_Data3.csv', 'rU') as csvfile:
    reader = csv.DictReader(csvfile)
    for row in reader:
        TEST_SENTENCES.append(row["Tweet"])
    try:
        [x.encode('utf-8') for x in TEST_SENTENCES]
    except:
        for rows in TEST_SENTENCES: #attempt to fix the problem 
            str=unicode(str, errors='replace')
```

**Comment by bfelbo** [comment]
Damn, that's really frustrating. Unicode can sadly be a mess and I might not the best to guide you on that.

One solution is to use something like [unidecode](https://pypi.org/project/Unidecode/) on each of the sentences and then remove sentences that are empty (make sure you use `.strip()` to disregard whitespace). Once you have this cleaned set of sentences without any unicode, you should be able to use DeepMoji without any issues!

**Comment by bfelbo** [comment]
Please feel free to reopen the issue if you're still having problems.
