### ISSUE TITLE
Typo DATASET vs. DATASETS?

### ISSUE THREAD

**Issue by cclauss** [bfelbo/DeepMoji#3]
Is the constant singular when it should be plural?  Or should it be `dset`?

flake8 testing of https://github.com/bfelbo/DeepMoji

$ __flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics__
```
./scripts/analyze_all_results.py:16:75: F821 undefined name 'DATASET'
    RESULT_PATHS = glob.glob('{}/{}_{}_*_results.txt'.format(RESULTS_DIR, DATASET, METHOD))
                                                                          ^

./scripts/analyze_all_results.py:30:32: F821 undefined name 'DATASET'
    print('Dataset: {}'.format(DATASET))
                               ^
```

**Comment by bfelbo** [comment]
It should be `dset`. Fixed. Thanks!

**Comment by cclauss** [comment]
@bfelbo Are you interested to get this code to Py3 or not so much?
