### ISSUE TITLE
problem with saving the intermediate weights in `class_avg_tune`

### ISSUE THREAD

**Issue by cnnjqzr** [bfelbo/DeepMoji#31]
Hi,

I find it difficult to save the intermediate weights  while calling `class_avg_tune_trainable`. I wish to keep track of the weights and not have only the last iterations' weights. Is that possible in the current implementation? I looked everywhere and it seems like it's not yet implemented. Am I missing or overlooking something?  I am currently trying to pretrain my own model on a different dataset that is labeled for 10 classes rather than the emoji one and then to further apply the transfer methods in deepmoji. 

Thank you!

**Comment by bfelbo** [comment]
That’s not implemented as it can take up a lot of space when the model trains for many epochs. It should be easy to change though. I’d suggest you create a new folder, where you save the weights with a different name for each epoch. You can modify the callback (or create a new one) to do that.

It would be awesome if you’d do a PR with this functionality in case others could use it as well.

**Comment by cnnjqzr** [comment]
Thanks for answering the question!
