### ISSUE TITLE
Return More Emoji

### ISSUE THREAD

**Issue by evanrosenbaum** [bfelbo/DeepMoji#33]
Is it possible to return a wider set of emoji than the 64 emoji defined here?

Would like to modify Deepmoji to be able to score text to use a wider set of emoji using the Twitter data used in the model.

**Comment by xwzhong** [comment]
I have same question with evanrosenbaum
did you use emoji occupation percent to select the emoji, eg:  use top 64 emoji occupy 99% percent of the text ? as we know, some of the emoji occur frequently.

**Comment by bfelbo** [comment]
It's not possible to return a wider set of emoji as DeepMoji was only trained on the top 64 emoji. For the next version of DeepMoji, we might include a larger set of emoji if that's requested by multiple people. It would be great if you could fill out in the survey in the README and state this potential improvement.

**Comment by bfelbo** [comment]
We took the top 64 emoji in terms of frequency as they occupied a very high percentage of the used emoji. I don't recall what percentage that was though.

**Comment by bfelbo** [comment]
I'm closing this issue as it's not possible as this time. However, feel free to write any related follow-up questions in this thread.

**Comment by L3o-pold** [comment]
If I understand correctly, if we want to use more than 64 emoji we need to create a new model?
