### ISSUE TITLE
correlation matrix calculation & data preprocessing

### ISSUE THREAD

**Issue by xwzhong** [bfelbo/DeepMoji#34]
hi, I have some confuse about the calculation of correlation matrix——how can we use pretraining test set to get the matrix? here is my assumption:
1. the each emoji, we have 10K test sample, use pretrained model to predict emoji distribution with 64 emoji, we get (10K, 64) matrix for each emoji
2. averaging in the axis 0, we get (1, 64) for each emoji and calculate the correlation between each other
do I understand corretly ?

what's more, labeling a text with emoji(s) in the original twitter, what if the emoji doesn't occur in selected emoji set(64)? drop it or keep in the text just as a char ?

looking forward your reply

**Comment by bfelbo** [comment]
Good question. Step 1 is correct. You then compute the correlations across all 10K observations. If you do the averaging you propose in step 2, then you'll lose the needed information to compute correlations.

Instead, you treat the 64 columns as separate features and use traditional methods to compute correlations across features. You can see a simple example of how that's done here: https://chrisalbon.com/machine_learning/feature_selection/drop_highly_correlated_features/

**Comment by xwzhong** [comment]
thanks much!
