### ISSUE TITLE
Attention weights

### ISSUE THREAD

**Issue by ryanleary** [bfelbo/DeepMoji#4]
Do you have a preferred/recommended way of exposing the attention weights at inference-time for visualizing the words/timesteps that were most heavily weighted for the prediction with this Keras implementation?

**Comment by bfelbo** [comment]
I haven't tried doing that for this Keras implementation, but you could do the following, which should be rather quick to implement:

- Add an argument, `return_att_weights`, to `deepmoji/attlayer.py` that allows you to return the attention weights in addition to the encoding.
- Modify `deepmoji_feature_encoding()` in `deepmoji/model_def.py` to use this argument.
- Modify `examples/encode_texts.py` to use the new additional prediction output and visualize the weights.

A PR with this functionality would be highly appreciated.

**Comment by ryanleary** [comment]
I'll work through this a bit. Is my understanding correct that I need to get the attention weight vector at each timestep? If no, we just get the attention weight vector of size 1x2304 (for a single example). How does one end up visualizing this vector? Sorry for my confusion here.

**Comment by bfelbo** [comment]
No, you don't need an attention weight vector pr. timestep. That's only for seq2seq models. This is a seq2vector model. You would only need to get the `att_weights` variable in `att_layer.py`.

**Comment by ryanleary** [comment]
So with the 2304-dimensional attention vector, do you just look at the portion of the vector that has the skip-connection to the original embedding and then project through that embedding to visualize the importance of the words in the input? Sorry -- this is the portion that's tripping me up, I have the code to expose the final attention weight vector.
