### ISSUE TITLE
Clarification

### ISSUE THREAD

**Issue by grehce** [bfelbo/DeepMoji#41]
How were the Kaggle and Youtube comments classified—were they cut off at 140 characters or was transfer learning applied with fewer but longer examples?

**Comment by bfelbo** [comment]
Sorry for the slow response. DeepMoji can be used for much longer texts than 140 characters. I don't remember the exact max length used for Kaggle and YouTube comments, but I'd imagine the 90th percentile of text lengths in the dataset should work well. They were definitely not cut off at 140 characters.
