### ISSUE TITLE
Emotional Impact Data

### ISSUE THREAD

**Issue by Megh-Thakkar** [bfelbo/DeepMoji#45]
The online demo highlights words based on their emotional impact. Is there a method to obtain numerical values or order of the impact of the words in the input?

**Comment by bfelbo** [comment]
The way we do it is to make a prediction without each word in the sentence. The words that when excluded make the prediction differ the most has the highest emotional impact. It shouldn't be too hard for you to implement using the standard DeepMoji model in this repo :)

**Comment by Megh-Thakkar** [comment]
That is really smart. Thank you.
