### ISSUE TITLE
'str' object has no attribute 'decode' in shorten_word from filter_utiles.py

### ISSUE THREAD

**Issue by mehdiHadji** [bfelbo/DeepMoji#46]
hi, 
am trying to convert your code to python 3.7, would you provide a version of `shorten_word` from `filter_utils.py` for python 3 since decode() is not supported for `str` please.

**Comment by bfelbo** [comment]
It sounds great that you're trying to convert the code to Python 3. You can see this [StackOverflow answer](https://stackoverflow.com/a/18403812/1452257) on how you'd do it in Python 3.

It'd be awesome if you submit a PR with your Python 3 version!
