### ISSUE TITLE
Live Demo is down

### ISSUE THREAD

**Issue by amitness** [bfelbo/DeepMoji#47]
The backend for the live demo on the website is down
![image](https://user-images.githubusercontent.com/8587189/59909450-69beda80-942f-11e9-9c12-9776914edc99.png)

**Comment by bfelbo** [comment]
Thanks! I’ll look into it.

**Comment by bfelbo** [comment]
Fixed!

**Comment by fluidityapp** [comment]
Hello the backend for the live demo on the website is down since at least yesterday Feb 17 2021
Would be great to give it life back ...🤞🏽🙏🤓
