### ISSUE TITLE
How did you relate data labels to emojis

### ISSUE THREAD

**Issue by plvenkat** [bfelbo/DeepMoji#48]
I have been trying to predict emojis using your data and your model as reference.But I am unable to relate the labels mentioned in your data with emojis.After training each dataset and getting models for each one,how do i relate all those  models to get a combined and new model to predict among all the 64 emoji codes

**Comment by bfelbo** [comment]
I'm sorry for the slow response. You can use https://github.com/bfelbo/DeepMoji/blob/master/examples/score_texts_emojis.py to predict emojis directly from any text. However, if you train on a new dataset then you'll no longer be predicting emojis, but be predicting the labels you provided in your training set.

I'm closing for now. Let me know if you have more questions :)
