### ISSUE TITLE
[Errno 2] No such file or directory: 'model/deepmoji_weights.hdf5'

### ISSUE THREAD

**Issue by wanitchayap** [bfelbo/DeepMoji#51]
I get this error when I try to run
`python scripts/download_weights.py`

**Comment by bfelbo** [comment]
Strange. What's your working directory when running the script?

**Comment by bfelbo** [comment]
Closing as I can't reproduce the error. Let me know if you're still facing this issue.

**Comment by tiimoS** [comment]
I had a similar issue after deleting the initial model. However, you can still get the file, by downloading it directly using the [dropbox link ](https://www.dropbox.com/s/xqarafsl6a8f9ny/deepmoji_weights.hdf5?dl=0#) and putting it in the ~/model directory.

**Comment by julienbeisel** [comment]
same problem on Mac OS, my working directory is the project root
