### ISSUE TITLE
How to start training deepmoji on a new language corpus?

### ISSUE THREAD

**Issue by sumegha19** [bfelbo/DeepMoji#55]
Hi Team!
Great work first of all!
I have gone through the code and implementation of Deepmoji. Sorry if I sound a little noob, but can you please give a little explanation on how to we feed data to deepmoji? What kind of file/format it desires ans what are the steps in line to be taken to start the training from scratch? KIndly help!

**Comment by bfelbo** [comment]
Depends on whether you want to train the DeepMoji architecture from scratch (see https://github.com/bfelbo/DeepMoji/blob/master/examples/imdb_from_scratch.py) or do transfer learning on a new task using finetuning (see https://github.com/bfelbo/DeepMoji/blob/master/examples/finetune_youtube_last.py).

If you have raw text data, you'll want to tokenize it first. If you use the same vocabulary as DeepMoji, you can use  https://github.com/bfelbo/DeepMoji/blob/master/examples/tokenize_dataset.py

**Comment by sumegha19** [comment]
Thanks a ton for the reply!!
