### ISSUE TITLE
Struggling to run the examples

### ISSUE THREAD

**Issue by yazoo178** [bfelbo/DeepMoji#6]
Hi, awesome work.

I'm having a hard time getting one of the examples to run (score_texts_emojis.py). It's throwing an error when compiling the regular expression in the tokenizer.py module:

RE_PATTERN = re.compile(ur'|'.join(IGNORED) + ur'|(' + ur'|'.join(TOKENS) + ur')',
                        re.UNICODE)

  File "C:\Users\W\Downloads\DeepMoji-master\DeepMoji-master\deepmoji\tokenizer.py", line 139, in <module>
    re.UNICODE)
  File "C:\Python27\lib\re.py", line 194, in compile
    return _compile(pattern, flags)
  File "C:\Python27\lib\re.py", line 251, in _compile
    raise error, v # invalid expression
sre_constants.error: bad character range

Here's the resulting regular expression before it attempts to compile it:

(u'\\s+|((?:https?://|www\\.)(?:[a-zA-Z]|[0-9]|[$-_@.&+]|[!*\\(\\),]|(?:%[0-9a-fA-F][0-9a-fA-F]))+|\\b[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\\.[a-zA-Z0-9-.]+\\b|[a-zA-Z]+[-_][a-zA-Z]+|#[a-zA-Z0-9_]+|@[a-zA-Z0-9_]+|(?:<+/?3+)+|\\-\\_\\-|x\\_x|\\^\\_\\^|o\\.o|o\\_o|\\(\\:|\\)\\:|\\)\\;|\\(\\;|\\>\\:\\-?D+|\\>\\:\\-?d+|\\>\\:\\-?p+|\\>\\:\\-?P+|\\>\\:\\-?v+|\\>\\:\\-?\\)+|\\>\\:\\-?o+|\\>\\:\\-?O+|\\>\\:\\-?\\(+|\\>\\:\\-?3+|\\>\\:\\-?\\/+|\\>\\:\\-?\\|+|\\>\\:\\-?\\\\+|\\>\\:\\,?D+|\\>\\:\\,?d+|\\>\\:\\,?p+|\\>\\:\\,?P+|\\>\\:\\,?v+|\\>\\:\\,?\\)+|\\>\\:\\,?o+|\\>\\:\\,?O+|\\>\\:\\,?\\(+|\\>\\:\\,?3+|\\>\\:\\,?\\/+|\\>\\:\\,?\\|+|\\>\\:\\,?\\\\+|\\>\\:\\^?D+|\\>\\:\\^?d+|\\>\\:\\^?p+|\\>\\:\\^?P+|\\>\\:\\^?v+|\\>\\:\\^?\\)+|\\>\\:\\^?o+|\\>\\:\\^?O+|\\>\\:\\^?\\(+|\\>\\:\\^?3+|\\>\\:\\^?\\/+|\\>\\:\\^?\\|+|\\>\\:\\^?\\\\+|\\>\\:\\\'?D+|\\>\\:\\\'?d+|\\>\\:\\\'?p+|\\>\\:\\\'?P+|\\>\\:\\\'?v+|\\>\\:\\\'?\\)+|\\>\\:\\\'?o+|\\>\\:\\\'?O+|\\>\\:\\\'?\\(+|\\>\\:\\\'?3+|\\>\\:\\\'?\\/+|\\>\\:\\\'?\\|+|\\>\\:\\\'?\\\\+|\\>\\:\\"?D+|\\>\\:\\"?d+|\\>\\:\\"?p+|\\>\\:\\"?P+|\\>\\:\\"?v+|\\>\\:\\"?\\)+|\\>\\:\\"?o+|\\>\\:\\"?O+|\\>\\:\\"?\\(+|\\>\\:\\"?3+|\\>\\:\\"?\\/+|\\>\\:\\"?\\|+|\\>\\:\\"?\\\\+|\\:\\-?D+|\\:\\-?d+|\\:\\-?p+|\\:\\-?P+|\\:\\-?v+|\\:\\-?\\)+|\\:\\-?o+|\\:\\-?O+|\\:\\-?\\(+|\\:\\-?3+|\\:\\-?\\/+|\\:\\-?\\|+|\\:\\-?\\\\+|\\:\\,?D+|\\:\\,?d+|\\:\\,?p+|\\:\\,?P+|\\:\\,?v+|\\:\\,?\\)+|\\:\\,?o+|\\:\\,?O+|\\:\\,?\\(+|\\:\\,?3+|\\:\\,?\\/+|\\:\\,?\\|+|\\:\\,?\\\\+|\\:\\^?D+|\\:\\^?d+|\\:\\^?p+|\\:\\^?P+|\\:\\^?v+|\\:\\^?\\)+|\\:\\^?o+|\\:\\^?O+|\\:\\^?\\(+|\\:\\^?3+|\\:\\^?\\/+|\\:\\^?\\|+|\\:\\^?\\\\+|\\:\\\'?D+|\\:\\\'?d+|\\:\\\'?p+|\\:\\\'?P+|\\:\\\'?v+|\\:\\\'?\\)+|\\:\\\'?o+|\\:\\\'?O+|\\:\\\'?\\(+|\\:\\\'?3+|\\:\\\'?\\/+|\\:\\\'?\\|+|\\:\\\'?\\\\+|\\:\\"?D+|\\:\\"?d+|\\:\\"?p+|\\:\\"?P+|\\:\\"?v+|\\:\\"?\\)+|\\:\\"?o+|\\:\\"?O+|\\:\\"?\\(+|\\:\\"?3+|\\:\\"?\\/+|\\:\\"?\\|+|\\:\\"?\\\\+|\\=\\-?D+|\\=\\-?d+|\\=\\-?p+|\\=\\-?P+|\\=\\-?v+|\\=\\-?\\)+|\\=\\-?o+|\\=\\-?O+|\\=\\-?\\(+|\\=\\-?3+|\\=\\-?\\/+|\\=\\-?\\|+|\\=\\-?\\\\+|\\=\\,?D+|\\=\\,?d+|\\=\\,?p+|\\=\\,?P+|\\=\\,?v+|\\=\\,?\\)+|\\=\\,?o+|\\=\\,?O+|\\=\\,?\\(+|\\=\\,?3+|\\=\\,?\\/+|\\=\\,?\\|+|\\=\\,?\\\\+|\\=\\^?D+|\\=\\^?d+|\\=\\^?p+|\\=\\^?P+|\\=\\^?v+|\\=\\^?\\)+|\\=\\^?o+|\\=\\^?O+|\\=\\^?\\(+|\\=\\^?3+|\\=\\^?\\/+|\\=\\^?\\|+|\\=\\^?\\\\+|\\=\\\'?D+|\\=\\\'?d+|\\=\\\'?p+|\\=\\\'?P+|\\=\\\'?v+|\\=\\\'?\\)+|\\=\\\'?o+|\\=\\\'?O+|\\=\\\'?\\(+|\\=\\\'?3+|\\=\\\'?\\/+|\\=\\\'?\\|+|\\=\\\'?\\\\+|\\=\\"?D+|\\=\\"?d+|\\=\\"?p+|\\=\\"?P+|\\=\\"?v+|\\=\\"?\\)+|\\=\\"?o+|\\=\\"?O+|\\=\\"?\\(+|\\=\\"?3+|\\=\\"?\\/+|\\=\\"?\\|+|\\=\\"?\\\\+|\\;\\-?D+|\\;\\-?d+|\\;\\-?p+|\\;\\-?P+|\\;\\-?v+|\\;\\-?\\)+|\\;\\-?o+|\\;\\-?O+|\\;\\-?\\(+|\\;\\-?3+|\\;\\-?\\/+|\\;\\-?\\|+|\\;\\-?\\\\+|\\;\\,?D+|\\;\\,?d+|\\;\\,?p+|\\;\\,?P+|\\;\\,?v+|\\;\\,?\\)+|\\;\\,?o+|\\;\\,?O+|\\;\\,?\\(+|\\;\\,?3+|\\;\\,?\\/+|\\;\\,?\\|+|\\;\\,?\\\\+|\\;\\^?D+|\\;\\^?d+|\\;\\^?p+|\\;\\^?P+|\\;\\^?v+|\\;\\^?\\)+|\\;\\^?o+|\\;\\^?O+|\\;\\^?\\(+|\\;\\^?3+|\\;\\^?\\/+|\\;\\^?\\|+|\\;\\^?\\\\+|\\;\\\'?D+|\\;\\\'?d+|\\;\\\'?p+|\\;\\\'?P+|\\;\\\'?v+|\\;\\\'?\\)+|\\;\\\'?o+|\\;\\\'?O+|\\;\\\'?\\(+|\\;\\\'?3+|\\;\\\'?\\/+|\\;\\\'?\\|+|\\;\\\'?\\\\+|\\;\\"?D+|\\;\\"?d+|\\;\\"?p+|\\;\\"?P+|\\;\\"?v+|\\;\\"?\\)+|\\;\\"?o+|\\;\\"?O+|\\;\\"?\\(+|\\;\\"?3+|\\;\\"?\\/+|\\;\\"?\\|+|\\;\\"?\\\\+|[a-zA-Z]+\\\'[a-zA-Z]+|(?i)Mr\\.|(?i)Ms\\.|(?i)Mrs\\.|(?i)Dr\\.|(?i)Prof\\.|\\b(?<!\\.)(?:[A-Za-z]\\.){2,}|[0-9]+|[a-zA-Z]+|\\(+|\\)+|\\<+|\\!+|\\?+|\\.+|\\,+|\\/+|\\\\+|\\\'+|\\\\+|\\"+|\\-+|\\_+|\\=+|\\\\+|\\\\+|\\\xa7+|\\|+|\\\xb4+|\\\u02c7+|\\\xb0+|\\[+|\\]+|\\<+|\\>+|\\{+|\\}+|\\~+|\\$+|\\^+|\\&+|\\*+|\\;+|\\:+|\\%+|\\++|\\\\+|x+|a+|3+|\\\u20ac+|\\`+|#+(?=#[a-zA-Z0-9_]+)|@+(?=@[a-zA-Z0-9_]+)|#+|@+|[\U0001f300-\U0001f64f\U0001f680-\U0001f6ff\n\u2600-\u26ff\u2700-\u27bf]|.)'

Thanks

**Comment by ryanleary** [comment]
I also had an issue with that (no workaround yet). It had to do with `[\U0001f300-\U0001f64f\U0001f680-\U0001f6ff]` in particular.

**Comment by devarsh13** [comment]
Changing 
```
RE_EMOJI = u"""[\U0001F300-\U0001F64F\U0001F680-\U0001F6FF
\u2600-\u26FF\u2700-\u27BF]""" to
RE_EMOJI = r"""[\U0001F300-\U0001F64F\U0001F680-\U0001F6FF
\u2600-\u26FF\u2700-\u27BF]"""
```
 
Worked for me 
Reference [https://stackoverflow.com/questions/44314290/python-regex-bad-character-range](url)

**Comment by bfelbo** [comment]
Strange. Thanks for posting a solution! Do you know:

1) What about your systems is causing this error?
2) Why this change fixes the issue?

**Comment by devarsh13** [comment]
I think this is because of a narrow python build
<img width="497" alt="screen shot 2017-09-08 at 11 26 41 pm" src="https://user-images.githubusercontent.com/8171462/30224718-75318fea-94ed-11e7-94d0-31786be5772d.png">
https://stackoverflow.com/questions/31603075/how-can-i-represent-this-regex-to-not-get-a-bad-character-range-error
