### ISSUE TITLE
How is emotional impact of words highlighted?

### ISSUE THREAD

**Issue by amitness** [bfelbo/DeepMoji#60]
Hi @bfelbo,

On the demo page, there is a section that shows the impact of words on the emoji predictions. How to calculate that?

![Screenshot from 2020-04-08 10-49-54](https://user-images.githubusercontent.com/8587189/78746505-c4a5cc00-7986-11ea-9bf2-74a14745bd96.png)

**Comment by bfelbo** [comment]
It's a bit hacky so I wouldn't recommend using it in production. We do the predictions w/o each word and see how much the distribution over predicted emojis change.

**Comment by amitness** [comment]
@bfelbo I see. So if I understand it correctly, is this how it's done?
- Say we have a sentence "I loved the application" and we run deepmoji to get top 5 predictions
- Then, we remove one word at a time and see the predictions
- The words whose removal changed the top 5 predictions are the important ones

If so, how do you give that score in the screenshot above? The importance reflected by the darker and lighter shades of purple.

**Comment by bfelbo** [comment]
Exactly. The shading is simply an interval over the difference. It was picked manually by trying out a couple of sentences and seeing what seemed to make sense.

Note that you can run all the predictions in a single batch, which will make this pretty fast even for long sentences.

**Comment by bfelbo** [comment]
I'm closing this for now as it's not related to the functionality of the repo, but to the demo. Hope my response was helpful!

**Comment by amitness** [comment]
It was. Thanks a lot.
