### ISSUE TITLE
cannot connect to remote server

### ISSUE THREAD

**Issue by KnowsCount** [bfelbo/DeepMoji#66]
it says:

![](https://knowscount-1304485449.cos.ap-shanghai.myqcloud.com/img/Screenshot%202021-02-28%20at%2020.03.03.png)

when I enter something that is not a part of `Examples`.

---

btw @bfelbo you looks exactly like Richard from Silicon Valley.

**Comment by bfelbo** [comment]
Thanks for letting me know, it's now up and running again :)
