### ISSUE TITLE
the link https://deepmoji.mit.edu/ is broken

### ISSUE THREAD

**Issue by JOY-SWang** [bfelbo/DeepMoji#73]
The link https://deepmoji.mit.edu/ is broken. Error code: 502-backend 
The security certificate has expired

**Comment by bfelbo** [comment]
Would love to get the demo working again, but the issue is that I also need to upgrade the codebase from Python 2 to Python 3. I'll do my best, but it's quite some effort to get it all upgraded so I sadly can't promise any timelines.

**Comment by bfelbo** [comment]
We've investigated and concluded that it's not feasible for us to get the online demo working again at this point. I've updated the README to show this.

It's awesome that you're still using our project these many years later 🙌 I hope the code is helpful in your endeavors.
